lang: "ko"
corpus_path: "data/corpus.txt"
repo_id: "junyeong-nero/synthetic-ocr-dataset"
output_dir: "data"
num_word_images: 100
num_doc_images: 100
num_table_images: 100
num_needle_images: 100
num_sentences: 100
sentence_corpus_path: "data/corpus.txt"
char_corpus_path: "data/all_chars_corpus.txt"
