lang: "th"
repo_id: "junyeong-nero/synthetic-ocr-images-thai"
num_sentences: 100000
font_path: "fonts/NotoSans-VariableFont_wdth,wght.ttf"
output_dir: "data"
num_sentence_images: 10
num_sentence_noise_images: 10
num_sentence_typos_images: 10
num_document_images: 10
num_document_noise_images: 10
num_document_typos_images: 10
num_table_images: 10
num_table_numeric_images: 10
num_table_typos_images: 10
num_needle_images: 10
